version: 2
jobs:
  build-and-deploy:
    working_directory: ~/workdir
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: update-pip
          command: 'pip install --upgrade pip'
      - run:
          name: install-mkdocs
          command: 'pip install mkdocs --user'
      - run:
          name: github-deploy 
          command: '~/.local/bin/mkdocs gh-deploy'
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build-and-deploy:
          context: writable-github
          filters:
            branches:
              only:
                - master
